ifeq ($(TARGET_BOOTLOADER_BOARD_NAME), swift)

LOCAL_PATH:= $(call my-dir)

include $(CLEAR_VARS)
LOCAL_PRELINK_MODULE := false
LOCAL_MODULE_PATH := $(TARGET_OUT_SHARED_LIBRARIES)/
LOCAL_SHARED_LIBRARIES := liblog libcutils
LOCAL_SRC_FILES += liblgdrm.c
LOCAL_MODULE := liblgdrm
LOCAL_MODULE_TAGS := optional

include $(BUILD_SHARED_LIBRARY)

endif